"""add user roles

Revision ID: 5202945c787d
Revises: ac6aa0c0dc4d
Create Date: 2025-02-09 22:24:47.577658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5202945c787d"
down_revision: Union[str, None] = "ac6aa0c0dc4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_user_role_type() -> None:
    """ 
    Функція створення кастомного типу для ролей користувачів
    """
    return sa.Enum("ADMIN", "USER", name="userrole")


def upgrade() -> None:
    # створення нового типу для ролей користувачів
    userrole = _create_user_role_type()
    userrole.create(op.get_bind())
    # додаємо новий стовпець до таблиці users
    op.add_column(
        "users", sa.Column("role", userrole, server_default="USER", nullable=False)
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
    # видаляємо тип userrole
    userrole().drop(op.get_bind())
